### ISSUE TITLE
checklist review for protos v20

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/LilyPad_Tri-Color_LED#1]
1) Is there a SparkFun Logo? [YES]
comment: Yes, but we should probably get rid of the old school "SparkFun Electronics" text object in schematic.

2) Also, the lilypad symbol in the schematic is old - it's actually spelled wrong... haha.

**Comment by lewispg228** [comment]
Also, although your schematic is fine as is, it may be cleaner to draw the GND connections like so

![image](https://cloud.githubusercontent.com/assets/601236/9371021/5f2cb888-4692-11e5-95d3-84c6c217f9cb.png)

**Comment by RobotGirlfriend** [comment]
Removed text object, updated logo symbol, tweaked schematic!

**Comment by lewispg228** [comment]
Hey Dia, I'm not seeing your new commit. (the last one I see is from Aug 13th). Could you please double check that you sync'd properly?

**Comment by RobotGirlfriend** [comment]
Sorry about that, had trouble syncing, think it's sorted now!

**Comment by lewispg228** [comment]
Looks great. Thanks!

**Comment by lewispg228** [comment]
Hey Dia,
I just went through the checklist again on this and it looks good. Just two things:

1) Please approve the last 6 DRC errors. PS thanks for approving all 500+ others - sheesh!

2) Now that orphans are turned on for your GND pours, there are some "dots" forming in the corners where the top ground pour extends beyond the tresrict drawings. 

![image](https://cloud.githubusercontent.com/assets/601236/11940288/f78c51b6-a7e4-11e5-95bb-ffba72dc4a9c.png)

After ratsnest it looks like this:

![image](https://cloud.githubusercontent.com/assets/601236/11940298/0e4b9d12-a7e5-11e5-8c3c-e3a9ecdc3a30.png)

You have two options: (a) alter the ground pour to be inside the trestrict (this is how it's solved for the bottom layer), or (b) extend the trestrict out a bit.

**Comment by RobotGirlfriend** [comment]
I'm not getting any more DRC errors, not sure what's happening there.
Ground pour moved.
I also added pin labels on the bottom of the board. It's crowded and ugly, but this one is for protos, so that Leah can see all of the possible silk (labels on top and bottom, board description on top and bottom), and decide what she wants to keep and what should go. It won't all be there when we go to reds.

**Comment by lewispg228** [comment]
Super old issue from super old revision. closing
