### ISSUE TITLE
double-check for v17 (protos)

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/LilyPad_Tri-Color_LED#3]
All really minor and quick. please take a look. thanks.

1) Is there a SparkFun Logo? [NO]
comment: no sparkfun logo in schematic

2) Is proper attribution given to the original designer? [NO]
comment: nope - need leah's name in there - or was it nate?

3) Are the fiducials in the lower right corner? [NO]
comment: no fids for aethetic reasons

4) If this design requires special ordering or production assembly instructions, have the symbols/packages been added with notes? (PCB thickness, humidity sensitivity, etc.) [NO]
comment: wouldn't be a bad idea to include instructions for purple and thin PCBs

5) Is there a correct version number in the copper (aligned properly with the edge of the PCB)? [NO]
comment: ommited due to aesthetic reasons (?) I sure wouldn't mind seeing it in there,  angela said it should be okay to include in bottom copper

6) Is there a note for a board thickness other than 0.63 inch?  [NO]
comment: missing thickness note

7) Are measurements included for outer dimension and standoffs (Eagle layer 47)? [NO]
comment: needs measures - maybe just the diamter? - also there is some left over dimensional drawings (out of position) on measures layer, might wand to clear those out

8) Is the designer name included in tDocu? [NO]
comment: missing

9) Is 'Revised by:' and 'Revisor Name' included in tDocu? [NO]
comment: missing

**Comment by AndyEngland521** [comment]
fixed and pushed

**Comment by lewispg228** [comment]
right on looks good thanks @AndyEngland521
